export const portfolios = [
  {
    id: 1,
    name: "US stocks",
    current: "42%",
    value: "$41,562.08",
    change: "36.40%",
    status: true,
    color: "#838FC2",
    text: "Vanguard Tax-exempt Bond Index ETF (VTEB)",
  },
  {
    id: 2,
    name: "Municipal bonds ",
    current: "17%",
    value: "$29,110.11",
    change: "9.04%",
    status: true,
    color: "#715A97",
    text: "Vanguard Total Stock Market ETF (VTI)",
  },
  {
    id: 3,
    name: "Emerge market bonds",
    current: "13%",
    value: "$11,110.11",
    change: "0.00%",
    status: true,
    color: "#503D3D",
    text: "Vanguard Total Stock Market ",
  },
  {
    id: 4,
    name: "Dividend growth stocks",
    current: "11%",
    value: "$2,000.55",
    change: "3.21%",
    status: true,
    color: "#87B3A5",
    text: "Schwab US TIPS ETF (SCHP)",
  },
  {
    id: 5,
    name: "Global stocks",
    current: "6%",
    value: "$2,000.55",
    change: "0.11%",
    status: false,
    color: "#B3A187",
    text: "Info about the cryptocurrency",
  },
  {
    id: 6,
    name: "TIPS",
    current: "8%",
    value: "$2,000.55",
    change: "1.11%",
    status: true,
    color: "#AF76AA",
    text: "Info about the cryptocurrency",
  },
  {
    id: 7,
    name: "Cryptocurrency",
    current: "3%",
    value: "$2,000.55",
    change: "3.08%",
    status: true,
    color: "#B63764",
    text: "Info about the cryptocurrency",
  },
]

export const statisticsData = [
  {
    id: 1,
    img: null,
    title: "ROI",
    subTitle: "Return on investment",
    price: "10,10%",
    change: null,
    text: null,
    status: true,
    icon: true,
  },
  {
    id: 2,
    img: null,
    title: "Annualized Return",
    subTitle: null,
    price: "4,58%",
    change: null,
    text: null,
    status: true,
    icon: true,
  },
  {
    id: 3,
    img: "/images/statistics/hst.png",
    title: "HST",
    subTitle: "US stocks",
    price: "$130,58",
    change: "3.08%",
    text: "Best performance",
    status: true,
    icon: false,
  },
  {
    id: 4,
    img: "/images/statistics/tgt.png",
    title: "TGT",
    subTitle: "US stocks",
    price: "$58,03",
    change: "35.19%",
    text: "Worst performance",
    status: false,
    icon: false,
  },
]

export const roboTrader = [
  {
    id: 1,
    date: "Friday, January 2, 2023",
    trade: [
      {
        event: "buy",
        asset: "HSB",
        img: "/images/stocks/HST.svg",
        type: "US Stock",
        price: "999,999.99",
        amount: "999,999.99",
        allocation: "99.99%",
      },
      {
        event: "sell",
        asset: "TGT",
        img: "/images/stocks/TGT.svg",
        type: "US Stock",
        price: "121.99",
        amount: "242.99",
        allocation: "",
      },
    ],
  },
  {
    id: 2,
    date: "Thursday, 1 January 2023",
    trade: [
      {
        event: "buy",
        asset: "Bitcoin",
        img: "/images/stocks/LC.svg",
        type: "Crypto",
        price: "32,119.00",
        amount: "125.99",
        allocation: "0.15%",
      },
      {
        event: "buy",
        asset: "Etherium",
        img: "/images/stocks/LC.svg",
        type: "Crypto",
        price: "1,822.99",
        amount: "20.99",
        allocation: "0.1%",
      },
      {
        event: "sell",
        asset: "ENB",
        img: "/images/stocks/LC.svg",
        type: "Municipal bonds",
        price: "141.54",
        amount: "141.54",
        allocation: "",
      },
      {
        event: "buy",
        asset: "TEAM",
        img: "/images/stocks/LC.svg",
        type: "Global stocks growth stocks",
        price: "125.59",
        amount: "125.59",
        allocation: "99.99%",
      },
    ],
  },
  {
    id: 3,
    date: "Wednesday, 31 December 2022",
    trade: [
      {
        event: "buy",
        asset: "Bitcoin",
        img: "/images/stocks/LC.svg",
        type: "Crypto",
        price: "32,119.00",
        amount: "125.99",
        allocation: "0.15%",
      },
      {
        event: "sell",
        asset: "TGT",
        img: "/images/stocks/TGT.svg",
        type: "US Stock",
        price: "121.99",
        amount: "242.99",
        allocation: "",
      },
    ],
  },
  {
    id: 4,
    date: "Wednesday, 31 December 2022",
    trade: [
      {
        event: "buy",
        asset: "Bitcoin",
        img: "/images/stocks/LC.svg",
        type: "Crypto",
        price: "32,119.00",
        amount: "125.99",
        allocation: "0.15%",
      },
      {
        event: "buy",
        asset: "Etherium",
        img: "/images/stocks/LC.svg",
        type: "Crypto",
        price: "1,822.99",
        amount: "20.99",
        allocation: "0.1%",
      },
    ],
  },
  {
    id: 5,
    date: "Monday, 29 December 2022",
    trade: [
      {
        event: "buy",
        asset: "TEAM",
        img: "/images/stocks/LC.svg",
        type: "Global stocks growth stocks",
        price: "125.59",
        amount: "125.59",
        allocation: "99.99%",
      },
    ],
  },
  {
    id: 6,
    date: "Saturday, 27 December 2022",
    trade: [
      {
        event: "sell",
        asset: "TEAM",
        img: "/images/stocks/LC.svg",
        type: "Global stocks growth stocks",
        price: "125.59",
        amount: "125.59",
        allocation: "99.99%",
      },
      {
        event: "sell",
        asset: "ENB",
        img: "/images/stocks/LC.svg",
        type: "Municipal bonds",
        price: "141.54",
        amount: "141.54",
        allocation: "",
      },
    ],
  },
  {
    id: 7,
    date: "Thursday, 25 December 2022",
    trade: [
      {
        event: "buy",
        asset: "Etherium",
        img: "/images/stocks/LC.svg",
        type: "Crypto",
        price: "1,822.99",
        amount: "20.99",
        allocation: "0.1%",
      },
      {
        event: "sell",
        asset: "TGT",
        img: "/images/stocks/TGT.svg",
        type: "US Stock",
        price: "121.99",
        amount: "242.99",
        allocation: "",
      },
    ],
  },
]

export const roboFunds = [
  {
    id: 1,
    img: "/images/robo/growth.svg",
    title: "Growth Financial",
    change: "32.7%",
    status: true,
    allocation: "30%",
    price: "$40,000.00",
    link: "#",
  },
  {
    id: 2,
    img: "/images/robo/mmcap.svg",
    title: "MMCAP",
    change: "32.7%",
    status: true,
    allocation: "5%",
    price: "$4,482.10",
    link: "#",
  },
  {
    id: 3,
    img: "/images/robo/vr.svg",
    title: "VR Global Offshore",
    change: "32.7%",
    status: true,
    allocation: "5%",
    price: "$4,482.10",
    link: "#",
  },
]
