export const sliderStocks = [
  {
    id: 1,
    symbol: "HST",
    price: "16.18",
    change: -99.99,
    image: "/images/stocks/HST.svg",
  },
  {
    id: 2,
    symbol: "LC",
    price: "1.18",
    change: 11.01,
    image: "/images/stocks/LC.svg",
  },
  {
    id: 1,
    symbol: "TGT",
    price: "8.5",
    change: -99.99,
    image: "/images/stocks/TGT.svg",
  },
  {
    id: 1,
    symbol: "ENB",
    price: "16.18",
    change: -99.99,
    image: "/images/stocks/ENB.svg",
  },
  {
    id: 1,
    symbol: "HST",
    price: "16.18",
    change: -99.99,
    image: "/images/stocks/HST.svg",
  },
  {
    id: 2,
    symbol: "LC",
    price: "12.18",
    change: 1.02,
    image: "/images/stocks/LC.svg",
  },
  {
    id: 1,
    symbol: "TGT",
    price: "8.5",
    change: -99.99,
    image: "/images/stocks/TGT.svg",
  },
  {
    id: 2,
    symbol: "LC",
    price: "12.18",
    change: 1.02,
    image: "/images/stocks/LC.svg",
  },
  {
    id: 1,
    symbol: "TGT",
    price: "8.5",
    change: -99.99,
    image: "/images/stocks/TGT.svg",
  },
]
